### ISSUE TITLE
[FP] 2 false positives

### ISSUE THREAD

**Issue by Oskicz** [re-ovo/Matrix-Issues#2498] opened 2022-02-23 01:04 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
1.18.x (purpur newest)
**Verbose messages**: 
**How/when does this happen**: 
**Video of false positive**: 
~~https://streamable.com/8fgqpa~~ fixed
https://streamable.com/8wv8bt
**Other information**: 

## Configuration Files
**Link to checks.yml file**:
i use https://github.com/QuantumSuite/MatrixChecks
(but i check on default and this same happens)

**Comment by Kylepoops** [comment] 2022-02-23 12:06
The first fp seems to be fixed in version 4.7.0-alpha01, waiting you to check

**Comment by Kylepoops** [comment] 2022-03-24 10:07
Can you reproduce it with `6.7.0 hotfix01`

**Closed** 2022-06-18 13:44 UTC
Labels: False Positive 🛠️
