### ISSUE TITLE
[FP] Movement

### ISSUE THREAD

**Issue by Rzaba222** [re-ovo/Matrix-Issues#2482] opened 2022-01-18 12:57 UTC
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server versio**: 1.18.1 Paper
**Verbose messages**: https://user-images.githubusercontent.com/88888842/149939658-c73f0eac-3844-4066-9637-03bcfa9f1f32.png
**How/when does this happen**: 10-20% of all time when trying to use (ppm) something while falliing near the ground
**Video of false positive**: https://streamable.com/ukgc8o
**Other information**: 

## Configuration Files
**[Link to checks.yml file]**: https://pastebin.com/SDH1vT2z

**Comment by DontNeedAName** [comment] 2022-01-23 09:40
Can confirm this. Often happens when doing mlgs.

**Comment by re-ovo** [comment] 2022-02-02 06:29
what's your matrix version? I guess it was caused by a incorrect right click fix for 1.17+ client, and it has been fixed in hotfix5+

**Closed by re-ovo** 2022-02-02 06:29 UTC
Labels: False Positive 🛠️
